version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - pip install -r requirements.txt
      - python -m pytest
  post_build:
    commands:
      - zip -r InventoryTest1.zip ./Backend/src
      - aws lambda update-function-code --function-name InventoryAllocationTest1 --zip-file fileb://InventoryTest1.zip
      # Backup
      - aws s3 cp InventoryTest1.zip s3://codebuild-inventory-test1/
      - aws s3 cp Backend/appspec.yml s3://codebuild-inventory-test1/configuration/
      - aws s3 cp Backend/buildspec.yml s3://codebuild-inventory-test1/configuration/
artifacts:
  files:
    - InventoryTest1.zip