version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - zip -r InventoryTest1.zip ./
      - aws s3 cp InventoryTest1.zip s3://codebuild-inventory-test1/
      - aws s3 cp Backend/appspec.yml s3://codebuild-inventory-test1/configuration/
      - aws s3 cp Backend/buildspec.yml s3://codebuild-inventory-test1/configuration/
      - CurrentVersion=$(echo $(aws lambda get-alias --function-name InventoryAllocationTest2 --name Test2 | grep FunctionVersion | tail -1 |tr -cd "[0-9]"))
  post_build:
    commands:
      - ls
      - aws lambda publish-version --function-name InventoryAllocationTest2
      - TargetVersion=$(echo $(aws lambda list-versions-by-function --function-name InventoryAllocationTest2 | grep Version | tail -1 | tr -cd "[0-9]"))
      - echo $CurrentVersion
      - echo $TargetVersion
      - sed -i -e "s/{{CurrentVersion}}/$CurrentVersion/g" s3://codebuild-inventory-test1/configuration/appspec.yml
      - sed -i -e "s/{{TargetVersion}}/$TargetVersion/g" s3://codebuild-inventory-test1/configuration/appspec.yml

artifacts:
  files:
    - "**/*"
