version: 0.0
Resources:
  - InventoryAllocationTest1:
      Type: AWS::Lambda::Function
      Properties:
        Name: "{{FUNCTION_NAME}}"
        Alias: "{{Alias}}"
        CurrentVersion: "{{CurrentVersion}}"
        TargetVersion: "{{TargetVersion}}"
#        CurrentVersion: "{{CurrentVersion}}"
#        TargetVersion: "{{TargetVersion}}"

# Hooks:
#  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
#  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"

