version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - ls
      - ls Backend
      - ls configuration

      - pip install -r ./configuration/requirements.txt
#      - python -m pytest
  post_build:
    commands:
      - zip -r InventoryTest1.zip ./Backend/src
      # Lambda関数名
      - FUNCTION_NAME="InventoryAllocationTest1"
      - echo "Name: $FUNCTION_NAME"
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://InventoryTest1.zip
      # Backup
      - aws s3 cp configuration/buildspec.yml s3://codebuild-inventory-test1/configuration/
      - aws s3 cp configuration/requirements.txt s3://codebuild-inventory-test1/configuration/

      - echo "Starting appspec.yml create process..."
    # エイリアス、現在のバージョン、ターゲットバージョンを取得
      - ALIAS=$(aws lambda list-aliases --function-name $FUNCTION_NAME --query 'Aliases[?FunctionVersion!=`$LATEST`].Name' --output text)
      - echo "Alias: $ALIAS"
      - CURRENT_VERSION=$(aws lambda list-versions-by-function --function-name $FUNCTION_NAME --query 'Versions[?Version!=`$LATEST`]|max_by(@, &to_number(Version)).Version' --output text)
      - echo "CurrentVersion: $CURRENT_VERSION"
      - TARGET_VERSION=$(aws lambda publish-version --function-name $FUNCTION_NAME --description "New version" --query 'Version' --output text)
      - echo "TargetVersion: $TARGET_VERSION"

    # AppSpecファイルのプレースホルダーを実際の値に置き換える
      - sed -i "s/{{Name}}/$FUNCTION_NAME/g"              configuration/appspec.yml
      - sed -i "s/{{Alias}}/$ALIAS/g"                     configuration/appspec.yml
      - sed -i "s/{{CurrentVersion}}/$CURRENT_VERSION/g"  configuration/appspec.yml
      - sed -i "s/{{TargetVersion}}/$TARGET_VERSION/g"    configuration/appspec.yml
      - cat configuration/appspec.yml
      - aws s3 cp configuration/appspec.yml s3://codebuild-inventory-test1/configuration/


artifacts:
  files:
    - InventoryTest1.zip
    - appspec.yml